name: "TBB Inverter Reader"
version: "1.0.0"
slug: "tbb_inverter"
description: "Lettura e scrittura RS485/MQTT per inverter TBB RiiO Sun II"
url: "https://github.com/CarloFalco/ha-tbb-inverter-addon/tree/main/tbb_inverter"
arch:
  - armv7
  - aarch64
  - amd64
init: false
uart: true
startup: services
boot: auto
options:
  serial_port: "/dev/ttyUSB0"
  baudrate: 9600
  poll_interval: 5
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_prefix: "tbb/inverter"
schema:
  serial_port: str
  baudrate: int
  poll_interval: int(1,3600)
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  mqtt_prefix: str
